#pragma once
#include "vision/VisionPipeline.h"

#include <opencv2/objdetect/objdetect.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/features2d.hpp>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <map>
#include <vector>
#include <string>
#include <math.h>

namespace grip {

/**
* A representation of the different types of blurs that can be used.
*
*/
#ifndef blur_type
#define blur_type
enum BlurType {
	BOX, GAUSSIAN, MEDIAN, BILATERAL
};
#endif
/**
* ballpipeline class.
* 
* An OpenCV pipeline generated by GRIP.
*/
class ballpipeline : public frc::VisionPipeline {
	private:
		cv::Mat cvResizeOutput;
		cv::Mat blurOutput;
		cv::Mat hsvThreshold0Output;
		cv::Mat hsvThreshold1Output;
		cv::Mat cvErode0Output;
		cv::Mat cvErode1Output;
		cv::Mat cvDilate0Output;
		cv::Mat cvDilate1Output;
		std::vector<cv::KeyPoint> findBlobs0Output;
		std::vector<cv::KeyPoint> findBlobs1Output;
		void cvResize(cv::Mat &, cv::Size &, double , double , int , cv::Mat &);
		void blur(cv::Mat &, BlurType &, double , cv::Mat &);
		void hsvThreshold(cv::Mat &, double [], double [], double [], cv::Mat &);
		void cvErode(cv::Mat &, cv::Mat &, cv::Point &, double , int , cv::Scalar &, cv::Mat &);
		void cvDilate(cv::Mat &, cv::Mat &, cv::Point &, double , int , cv::Scalar &, cv::Mat &);
		void findBlobs(cv::Mat &, double , double [], bool , std::vector<cv::KeyPoint> &);

	public:
		ballpipeline();
		void Process(cv::Mat& source0) override;
		cv::Mat* GetCvResizeOutput();
		cv::Mat* GetBlurOutput();
		cv::Mat* GetHsvThreshold0Output();
		cv::Mat* GetHsvThreshold1Output();
		cv::Mat* GetCvErode0Output();
		cv::Mat* GetCvErode1Output();
		cv::Mat* GetCvDilate0Output();
		cv::Mat* GetCvDilate1Output();
		std::vector<cv::KeyPoint>* GetFindBlobs0Output();
		std::vector<cv::KeyPoint>* GetFindBlobs1Output();
};


} // end namespace grip


