#pragma once
#include "vision/VisionPipeline.h"

#include <opencv2/objdetect/objdetect.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/features2d.hpp>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <map>
#include <vector>
#include <string>
#include <math.h>

namespace grip {

/**
* A representation of the different types of blurs that can be used.
*
*/
#ifndef blur_type
#define blur_type
enum BlurType {
	BOX, GAUSSIAN, MEDIAN, BILATERAL
};
#endif
/**
*  class.
* 
* An OpenCV pipeline generated by GRIP.
*/
class retro : public frc::VisionPipeline {
	private:
		cv::Mat cvResizeOutput;
		cv::Mat blurOutput;
		cv::Mat hsvThresholdOutput;
		cv::Mat cvErodeOutput;
		cv::Mat cvDilateOutput;
		std::vector<cv::KeyPoint> findBlobsOutput;
		void cvResize(cv::Mat &, cv::Size &, double , double , int , cv::Mat &);
		void blur(cv::Mat &, BlurType &, double , cv::Mat &);
		void hsvThreshold(cv::Mat &, double [], double [], double [], cv::Mat &);
		void cvErode(cv::Mat &, cv::Mat &, cv::Point &, double , int , cv::Scalar &, cv::Mat &);
		void cvDilate(cv::Mat &, cv::Mat &, cv::Point &, double , int , cv::Scalar &, cv::Mat &);
		void findBlobs(cv::Mat &, double , double [], bool , std::vector<cv::KeyPoint> &);

	public:
		retro();
		void Process(cv::Mat& source0) override;
		cv::Mat* GetCvResizeOutput();
		cv::Mat* GetBlurOutput();
		cv::Mat* GetHsvThresholdOutput();
		cv::Mat* GetCvErodeOutput();
		cv::Mat* GetCvDilateOutput();
		std::vector<cv::KeyPoint>* GetFindBlobsOutput();
};


} // end namespace grip


